services:

  django_app:
    build: .
    volumes:
      - ./test_wallet:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    command: bash -c "sleep 5 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: wallet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1201
    ports:
      - "5432:5432"